/*
@TargetNode='localhost'
@GeneratedBy=Anon
@GenerationDate=10/26/2022 20:33:57
@GenerationHost=Anon
*/

instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
Ensure = "Present";
 ModuleName = "PSDscResources";
 ModuleVersion = "2.12.0.0";
 StartupType = "Automatic";
 SourceInfo = "C:\\DSC\\Crowdstrike\\Crowdstrike\\Crowdstrike.ps1::7::9::Service";
 ResourceID = "[Service]CrowdstrikeFalconAgent";
 Name = "CSFalconService";
 State = "Running";
 ConfigurationName = "Crowdstrike";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="Anon";

                        GenerationDate="10/26/2022 20:33:57";

                        GenerationHost="Anon";

                        Name="Crowdstrike";

                    };
